export const ActionTypes = {
  All_PRODUCT: "All_PRODUCT",

  SET_CATEGORY: "SET_CATEGORY",

  SET_PRODUCT: "SET_PRODUCT",

  ADD_TO_CART: "ADD_TO_CART",

  SET_DETAILS: "SET_DETAILS",

  ADD_WISH: "ADD_WISH",

  SET_SEARCH: "SET_SEARCH",

  DELETE_DATA: "DELETE_DATA",

  SET_CATEGORY_PRODUCT: "SET_CATEGORY_PRODUCT",

  WISH_DELETE_DATA: "WISH_DELETE_DATA",

  SET_DEC: "SET_DEC",

  SET_INC: "SET_INC",

  REMOVE_ALL_CART: "REMOVE_ALL_CART",

  CLEAN_UP: "CLEAN_UP",

  ORDER_ITEM: "ORDER_ITEM",

  CANCEL_ORDER_ITEM: "CANCEL_ORDER_ITEM",

  SET_ADDRESS: "SET_ADDRESS",

  RMV_ADDRESS: "RMV_ADDRESS",

  LOG_IN: "LOG_IN",

  LOG_IN_REMOVE: "LOG_IN_REMOVE",

  HOME_DESIGN_DETAILS: "HOME_DESIGN_DETAILS",

  BUY_SINGLE_PRODUCT: "BUY_SINGLE_PRODUCT",
};
